# Generated by Django 5.1.9 on 2025-05-16 14:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_modified_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='modified_by',
        ),
        migrations.AddField(
            model_name='post',
            name='modified_by',
            field=models.ManyToManyField(related_name='modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
